dropout_rate: 0.5
cell_size: 256
attn_size: 256
embedding_size: 128

layers: 1
bidir: True
use_lstm: False
max_output_len: 25
max_input_len: 25
weight_scale: 0.1

data_dir: data/btec
model_dir: models/btec_reinforce
log_file: models/btec_reinforce/log.txt
batch_size: 32
dev_prefix: dev

loss_function: 'reinforce'
baseline_steps: 2000
reinforce_baseline: True
rollouts: 0
partial_rewards: False

optimizer: 'sgd'
learning_rate: 0.01
learning_rate_decay_factor: 0.9
decay_every_n_epoch: 1
decay_after_n_epoch: 5

reset: True

steps_per_checkpoint: 200
steps_per_eval: 200

max_gradient_norm: 1.0
max_epochs: 15
batch_mode: 'standard'
read_ahead: 10

encoders:
  - name: fr

decoder:
    name: en
